// ─── Topic Key ──────────────────────────────────────────────────────────────
// Composite key for routing messages to the correct session.
// Replaces chatId-only keying to support concurrent sessions via Forum Topics.

export interface TopicKey {
  chatId: number;
  /** Telegram message_thread_id — present when using Forum Topics. */
  threadId?: number;
  /** For flat-chat job isolation — ensures jobs don't share interactive session keys. */
  jobId?: string;
}

/** Serialisable form for use as Map key. */
export type TopicKeyString = string;

export function topicKeyStr(key: TopicKey): TopicKeyString {
  if (key.threadId != null) return `${key.chatId}:${key.threadId}`;
  if (key.jobId) return `${key.chatId}:job:${key.jobId}`;
  return `${key.chatId}`;
}

export function parseTopicKey(str: TopicKeyString): TopicKey {
  if (str.includes(":job:")) {
    const [chatId, , jobId] = str.split(":");
    return { chatId: Number(chatId), jobId };
  }
  const parts = str.split(":");
  if (parts.length === 2) {
    return { chatId: Number(parts[0]), threadId: Number(parts[1]) };
  }
  return { chatId: Number(parts[0]) };
}

// ─── Telegram Bot API Types ─────────────────────────────────────────────────

export interface TelegramUser {
  id: number;
  is_bot: boolean;
  first_name: string;
  last_name?: string;
  username?: string;
}

export interface TelegramChat {
  id: number;
  type: "private" | "group" | "supergroup" | "channel";
  first_name?: string;
  last_name?: string;
  username?: string;
  title?: string;
}

export interface TelegramPhotoSize {
  file_id: string;
  file_unique_id: string;
  width: number;
  height: number;
  file_size?: number;
}

export interface TelegramDocument {
  file_id: string;
  file_unique_id: string;
  file_name?: string;
  mime_type?: string;
  file_size?: number;
}

export interface TelegramMessage {
  message_id: number;
  from?: TelegramUser;
  chat: TelegramChat;
  date: number;
  text?: string;
  caption?: string;
  photo?: TelegramPhotoSize[];
  document?: TelegramDocument;
  reply_to_message?: TelegramMessage;
  /** Present when the message is inside a Forum Topic. */
  message_thread_id?: number;
  /** True when the message is a topic message (not the General topic). */
  is_topic_message?: boolean;
  /** Service message: forum topic was closed. */
  forum_topic_closed?: Record<string, never>;
  /** Service message: forum topic was reopened. */
  forum_topic_reopened?: Record<string, never>;
}

export interface TelegramCallbackQuery {
  id: string;
  from: TelegramUser;
  message?: TelegramMessage;
  chat_instance: string;
  data?: string;
}

export interface TelegramInlineKeyboardButton {
  text: string;
  callback_data?: string;
  url?: string;
}

export interface TelegramInlineKeyboardMarkup {
  inline_keyboard: TelegramInlineKeyboardButton[][];
}

export interface TelegramBotCommand {
  command: string;
  description: string;
}

export interface TelegramForumTopic {
  message_thread_id: number;
  name: string;
  icon_color?: number;
}

export interface TelegramChatInfo extends TelegramChat {
  is_forum?: boolean;
}

export interface TelegramUpdate {
  update_id: number;
  message?: TelegramMessage;
  channel_post?: TelegramMessage;
  callback_query?: TelegramCallbackQuery;
}

export interface TelegramGetUpdatesResponse {
  ok: boolean;
  result: TelegramUpdate[];
}

export interface TelegramSendMessageResponse {
  ok: boolean;
  result?: TelegramMessage;
  description?: string;
}

// ─── Access Control ──────────────────────────────────────────────────────────

export type AccessPolicy = "pairing" | "allowlist" | "open";

export interface AccessState {
  policy: AccessPolicy;
  /** Allowlisted Telegram user IDs */
  allowlist: number[];
  /** Pending pairing codes: code → { userId, expiresAt } */
  pendingCodes: Map<string, PendingPairing>;
}

export interface PendingPairing {
  userId: number;
  chatId: number;
  username?: string;
  firstName: string;
  expiresAt: number; // epoch ms
}

// ─── Channel State ────────────────────────────────────────────────────────────

export interface ChannelState {
  botToken: string;
  botInfo: TelegramUser | null;
  access: AccessState;
  /** Track last update ID for long-polling */
  lastUpdateId: number;
  /** Active reply context: maps message_id → chat_id */
  activeContext: ActiveContext | null;
}

export interface ActiveContext {
  chatId: number;
  messageId: number;
  userId: number;
  username?: string;
}

// ─── Session Types (Orchestrator) ────────────────────────────────────────────

export type PermissionMode = "normal" | "plan" | "auto-accept";

export interface SessionInfo {
  sessionId: string;
  chatId: number;
  cwd: string;
  name?: string;
  title?: string; // Auto-generated by Claude CLI
  model?: string;
  permissionMode?: PermissionMode;
  totalCost: number;
  totalTurns: number;
  createdAt: number;
  lastActiveAt: number;
  /** Forum Topic thread ID this session is associated with. */
  threadId?: number;
  /** Message ID of the pinned status message in the session's forum topic. */
  pinnedMessageId?: number;
}

export interface DirectoryBookmark {
  path: string;
  name: string;
}

// ─── Scheduling ──────────────────────────────────────────────────────────────

export interface ScheduledJob {
  id: string;
  chatId: number;
  cwd: string;
  cronExpr: string;
  prompt: string;
  name?: string;
  recurring: boolean;
  sessionId?: string;
  createdAt: number;
  lastRunAt?: number;
  nextRunAt?: number;
  runCount: number;
  expiresAt?: number;
  enabled: boolean;
  /** Forum Topic thread ID for this job's output. */
  threadId?: number;
}

// ─── Permission Relay Protocol ───────────────────────────────────────────────

export interface RelayPromptRequest {
  chatId: number;
  requestId: string;
  toolName: string;
  toolInput: Record<string, unknown>;
  /** Forum Topic thread ID for routing the permission prompt. */
  threadId?: number;
}

export interface RelayPromptResponse {
  behavior: "allow" | "deny";
  updatedInput?: unknown;
  message?: string;
}

// ─── Claude CLI NDJSON Message Types ─────────────────────────────────────────

export interface ClaudeInitMessage {
  type: "system";
  subtype: "init";
  session_id: string;
  tools?: string[];
}

export interface ClaudeAssistantMessage {
  type: "assistant";
  message: {
    id: string;
    role: "assistant";
    content: ClaudeContentBlock[];
    model?: string;
    stop_reason?: string | null;
  };
}

export interface ClaudeResultMessage {
  type: "result";
  subtype: "success" | "error";
  session_id: string;
  total_cost_usd?: number;
  is_error?: boolean;
  duration_ms?: number;
  num_turns?: number;
}

export type ClaudeContentBlock =
  | { type: "text"; text: string }
  | { type: "tool_use"; name: string; id: string; input: unknown };

export type ClaudeMessage =
  | ClaudeInitMessage
  | ClaudeAssistantMessage
  | ClaudeResultMessage
  | { type: string; [key: string]: unknown };

// ─── Env Config ───────────────────────────────────────────────────────────────

export interface Config {
  botToken: string;
  dataDir: string;
  allowlistPath: string;
  pollIntervalMs: number;
  pairingCodeTtlMs: number;
  maxFileSizeBytes: number;
}
